### ISSUE TITLE
Error when trying to upload the modified manifest

### ISSUE THREAD

**Issue by RainerAtSpirit** [AzureADSamples/SinglePageApp-jQuery-DotNet#2]
In step **Step 3** while trying to upload the modified manifest I'm getting the following from azure.

```cmd
ParameterValidationException=Invalid parameters provided; BadRequestException=One or more extension property values specified are invalid.;
```

Starting from scratch and trying to download and upload an unmodified manifest leads to the same result. Any hints how to proceed?

**Comment by PugnetGuillaume** [comment]
I am facing the same issue : downloading the current manifest and uploading it back give me this error.

**Comment by skwan** [comment]
We're looking into this...

**Comment by skwan** [comment]
We've deployed a fix to AAD and this issue should be resolved now.

**Comment by RainerAtSpirit** [comment]
@skwan I can confirm that this is resolved. Thanks.
